name: Publish Package to npmjs

on:
  release:
    types:
      - published
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lodckfile

      - name: Run tests
        run: pnpm run test:ci

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        if: ${{ success() }}
        run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
